max_width = 120
tab_spaces = 2
# comment_width = 100
# newline_style = "Unix"
# reorder_impl_items = true
# format_strings = true
# format_macro_matchers = true
# format_macro_bodies = true
# group_imports = "StdExternalCrate"
# blank_lines_upper_bound = 1
# use_field_init_shorthand = true
# control_brace_style = "AlwaysSameLine"
